name:                storm
version:             0.1.0.0
license:             BSD
author:              ""
maintainer:          ""
copyright:           ""

extra-source-files:
- README.md
- ChangeLog.md

description: test

dependencies:
- base >= 4.7 && < 5
- filepath
- directory
- fgl
- aeson 
- lens-aeson
- lens
- attoparsec
- conduit 
- network 
- transformers 
- mtl 
- bytestring 
- text 
- composition-extra
- format-numbers
- containers
- random
- async 
- stm 

library:
  source-dirs: src

executables:
  storm:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - storm

tests:
  storm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - storm
